import "./globals.css";
import { DM_Sans, Inter } from "next/font/google";
import { Providers } from "./providers";
import { cn } from "@/lib/utils";

const inter = DM_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={cn("dark", inter.className)}>
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
